export * from '@dialog/Dialog'
export {default as Dialog} from '@dialog/Dialog'
export * from '@dialog/Content'
export {default as DialogContent} from '@dialog/Content'
export * from '@dialog/Title'
export {default as DialogTitle} from '@dialog/Title'
export * from '@dialog/Tails'
export {default as TailsDialog} from '@dialog/Tails'
export * from '@dialog/Tails/types'
